name: build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Scala build system
      uses: olafurpg/setup-scala@v11
      with:
        java-version: 1.8
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        lfs: false
    - name: Build
      run: sbt +compile
    - name: Publish
      env:
        SONATYPE_USERNAME: '${{ secrets.SONATYPE_USERNAME }}'
        SONATYPE_PASSWORD: '${{ secrets.SONATYPE_PASSWORD }}'
        PGP_PASSPHRASE: '${{ secrets.PGP_PASSPHRASE }}'
        PGP_SECRET: '${{ secrets.PGP_SECRET }}'
      run: sbt ci-release
      
