name: CI build

on:
  push:
    tags:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Scala build system
      uses: olafurpg/setup-scala@v11
      with:
        java-version: 1.8
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        lfs: false
    - name: Build and Publish
      env:
        SONATYPE_USER: '${{ secrets.SONATYPE_USER }}'
        SONATYPE_PASS: '${{ secrets.SONATYPE_PASS }}'
      run: sbt compile publish
      
